Repository mosa/MOSA-Project, pull requests merged in 2023-08, with the labels that each got.

#1102 WIP - BareMetal
  Source/Mosa.BareMetal.HelloWorld.x86/Boot.cs
  Source/Mosa.Compiler.Framework/Linker/MosaLinker.cs
  Source/Mosa.Demo.CoolWorld.x86/Plugs/EnvironmentPlug.cs
  Source/Mosa.Demo.HelloWorld.x86/Plugs/EnvironmentPlug.cs
  Source/Mosa.Demo.SVGAWorld.x86/Plugs/EnvironmentPlug.cs
  Source/Mosa.Demo.TestWorld.x64/Plugs/EnvironmentPlug.cs
  Source/Mosa.Demo.TestWorld.x86/Plugs/EnvironmentPlug.cs
  Source/Mosa.DeviceSystem/HAL.cs
  Source/Mosa.Kernel.BareMetal.x86/VGAConsole.cs
  Source/Mosa.Kernel.BareMetal/Boot.cs
  Source/Mosa.Kernel.BareMetal/BootOptions.cs
  Source/Mosa.Kernel.BareMetal/HardwareAbstractionLayer.cs
  Source/Mosa.Kernel.BareMetal/Kernel.cs
  Source/Mosa.Kernel.BareMetal/Korlib/ConsolePlug.cs
  Source/Mosa.Kernel.BareMetal/Korlib/DebugPlug.cs
  Source/Mosa.Kernel.BareMetal/Korlib/EnvironmentPlug.cs
  Source/Mosa.Kernel.BareMetal/Korlib/Notes.md
  Source/Mosa.Kernel.BareMetal/ScreenColor.cs
  Source/Mosa.Kernel.BareMetal/ScreenConsole.cs
  Source/Mosa.Plug.Korlib/System/EnvironmentPlug.cs
  Source/Mosa.UnitTests.BareMetal.x86/Boot.cs
  Source/Mosa.UnitTests.BareMetal.x86/UnitTestEngine.cs
Labels: WIP

#1108 WIP - ARMv8A32
  Source/Data/ARMv8A32-Instructions.json
  Source/Mosa.BareMetal.HelloWorld.ARMv8A32/Mosa.BareMetal.HelloWorld.ARMv8A32.csproj
  Source/Mosa.Compiler.Framework/CompilerEvent.cs
  Source/Mosa.Compiler.Framework/OpcodeEncoder.cs
  Source/Mosa.Linux.sln
  Source/Mosa.Platform.ARMv8A32/Architecture.cs
  Source/Mosa.Platform.ARMv8A32/Instructions/Bl.cs
  Source/Mosa.Platform.ARMv8A32/Transforms/IR/CallDirect.cs
  Source/Mosa.Platform.ARMv8A32/Transforms/IR/StoreObject.cs
  Source/Mosa.Tool.Compiler/Properties/launchSettings.json
  Source/Mosa.sln
Labels: Feature

#1117 Pass Boot Options string to the Kernel
  Source/Docs/command-line-arguments.rst
  Source/Docs/settings-options.rst
  Source/Mosa.BareMetal.HelloWorld/Program.cs
  Source/Mosa.Compiler.Common/BinaryWriterExtensions.cs
  Source/Mosa.Compiler.Framework/BaseCompilerStage.cs
  Source/Mosa.Compiler.Framework/Compiler.cs
  Source/Mosa.Compiler.Framework/CompilerStages/BootOptionStage.cs
  Source/Mosa.Compiler.Framework/CompilerStages/ExceptionTableStage.cs
  Source/Mosa.Compiler.Framework/CompilerStages/MetadataStage.cs
  Source/Mosa.Compiler.Framework/CompilerStages/MethodTableStage.cs
  Source/Mosa.Compiler.Framework/Intrinsics/GetBootOptions.cs
  Source/Mosa.Compiler.Framework/Linker/Elf/Dwarf/Nodes.cs
  Source/Mosa.Compiler.Framework/Linker/Elf/Dwarf/WriterExtensions.cs
  Source/Mosa.Compiler.Framework/Metadata.cs
  Source/Mosa.Kernel.BareMetal/Boot.cs
  Source/Mosa.Kernel.BareMetal/BootOptions.cs
  Source/Mosa.Kernel.BareMetal/BootSettings.cs
  Source/Mosa.Kernel.BareMetal/Debug.cs
  Source/Mosa.Runtime/Intrinsic.cs
  Source/Mosa.UnitTests.BareMetal.x86/Boot.cs
  Source/Mosa.Utility.Configuration/CommandLineArguments.cs
  Source/Mosa.Utility.Configuration/MOSASettings.cs
  Source/Mosa.Utility.Configuration/Name.cs
  Source/Mosa.Utility.Launcher/FileHunter.cs
  Source/Mosa.Utility.Launcher/Starter.cs
Labels: Feature

#1119 Added BootLoader Timeout Setting
  Source/Docs/command-line-arguments.rst
  Source/Mosa.BareMetal.HelloWorld/Program.cs
  Source/Mosa.Kernel.BareMetal/BootOptions.cs
  Source/Mosa.Kernel.BareMetal/MultibootSpecification/MultibootV1.cs
  Source/Mosa.Utility.Configuration/CommandLineArguments.cs
  Source/Mosa.Utility.Configuration/MOSASettings.cs
  Source/Mosa.Utility.Configuration/Name.cs
  Source/Mosa.Utility.Launcher/Builder.cs
Labels: Feature

#1123 Implement Multiboot v2
  Source/Docs/command-line-arguments.rst
  Source/Mosa.BareMetal.HelloWorld/AppManager.cs
  Source/Mosa.BareMetal.HelloWorld/Apps/BootInfo.cs
  Source/Mosa.Compiler.Framework/Platform/BaseMultibootStage.cs
  Source/Mosa.DeviceDriver/ISA/ACPI/ACPIDriver.cs
  Source/Mosa.DeviceDriver/ISA/ACPI/IOAPICEntry.cs
  Source/Mosa.DeviceDriver/ISA/ACPI/LongLocalAPICEntry.cs
  Source/Mosa.DeviceDriver/ISA/ACPI/MADT.cs
  Source/Mosa.DeviceDriver/ISA/ACPI/ProcessorLocalAPICEntry.cs
  Source/Mosa.DeviceDriver/ISA/ACPI/RSDPDescriptor.cs
  Source/Mosa.DeviceDriver/ISA/ACPI/RSDPDescriptor20.cs
  Source/Mosa.DeviceDriver/ISA/ACPI/RSDT.cs
  Source/Mosa.DeviceDriver/ISA/ACPI/XSDT.cs
  Source/Mosa.DeviceDriver/Setup.cs
  Source/Mosa.DeviceSystem/BaseHardwareAbstraction.cs
  Source/Mosa.DeviceSystem/HAL.cs
  Source/Mosa.Kernel.BareMetal/Boot.cs
  Source/Mosa.Kernel.BareMetal/BootMemory/BootMemoryMap.cs
  Source/Mosa.Kernel.BareMetal/BootOptions.cs
  Source/Mosa.Kernel.BareMetal/HardwareAbstractionLayer.cs
  Source/Mosa.Kernel.BareMetal/Multiboot.cs
  Source/Mosa.Kernel.BareMetal/MultibootSpecification/MultibootV1.cs
  Source/Mosa.Kernel.BareMetal/MultibootSpecification/MultibootV1MemoryMapEntry.cs
  Source/Mosa.Kernel.BareMetal/MultibootSpecification/MultibootV1VBEEntry.cs
  Source/Mosa.Kernel.BareMetal/MultibootSpecification/MultibootV2.cs
  Source/Mosa.Kernel.BareMetal/MultibootSpecification/MultibootV2MemoryMapEntry.cs
  Source/Mosa.Tool.Explorer/MainForm.cs
  Source/Mosa.Tool.Launcher/MainWindow.axaml
  Source/Mosa.Tool.Launcher/MainWindow.axaml.cs
  Source/Mosa.Utility.Configuration/CommandLineArguments.cs
  Source/Mosa.Utility.Configuration/MOSASettings.cs
  Source/Mosa.Utility.Configuration/Name.cs
  Source/Mosa.Utility.Launcher/Builder.cs
  Source/Mosa.Utility.Launcher/Starter.cs
Labels: Feature, WIP

#1128 Fixed SCCP and Debug Engine Improvements
  Source/Docs/command-line-arguments.rst
  Source/Docs/faq.rst
  Source/Docs/images/mosa-demo-graphicalworld.png
  Source/Docs/images/mosa-launcher.png
  Source/Docs/license.rst
  Source/Docs/settings-options.rst
  Source/Docs/unit-tests.rst
  Source/Mosa.BareMetal.HelloWorld.x86/Boot.cs
  Source/Mosa.BareMetal.HelloWorld.x86/Mosa.BareMetal.HelloWorld.x86.csproj
  Source/Mosa.Compiler.Framework/Analysis/SparseConditionalConstantPropagation.cs
  Source/Mosa.Kernel.BareMetal/Boot.cs
  Source/Mosa.Kernel.BareMetal/BootOptions.cs
  Source/Mosa.Kernel.BareMetal/BootSettings.cs
  Source/Mosa.Kernel.BareMetal/Serial.cs
  Source/Mosa.Utility.Configuration/CommandLineArguments.cs
  Source/Mosa.Utility.Configuration/MOSASettings.cs
  Source/Mosa.Utility.Configuration/Name.cs
  Source/Mosa.Utility.Launcher/Builder.cs
  Source/Mosa.Utility.Launcher/Starter.cs
  Source/Mosa.Utility.UnitTests/Program.cs
  Source/Mosa.Utility.UnitTests/UnitTestEngine.cs
  Source/Mosa.Utility.UnitTests/UnitTestSystem.cs
  Source/Mosa.Workspace.Experiment.Debug/Program.cs
Labels: Unit Test, WIP

#1129 Switch to BareMetal Unit Test Engine + Fix for Hello World
  Demos/Run-Demo.TestWorld.x86.bat
  Source/Docs/command-line-arguments.rst
  Source/Mosa.BareMetal.HelloWorld.x86/Boot.cs
  Source/Mosa.Compiler.Framework/Analysis/SparseConditionalConstantPropagation.cs
  Source/Mosa.Compiler.Framework/Platform/BaseMultibootStage.cs
  Source/Mosa.Demo.TestWorld.x86/Boot.cs
  Source/Mosa.Kernel.BareMetal/BootOptions.cs
  Source/Mosa.Kernel.BareMetal/Debug.cs
  Source/Mosa.Kernel.BareMetal/InitialGCMemory.cs
  Source/Mosa.Platform.x64/CompilerStages/MultibootStage.cs
  Source/Mosa.Platform.x86/CompilerStages/MultibootStage.cs
  Source/Mosa.Plug.Korlib.x86/System.Runtime.Intrinsics.X86/PopcntPlug.cs
  Source/Mosa.Plug.Korlib/System.Runtime.CompilerServices/RuntimeHelpersPlug.cs
  Source/Mosa.UnitTests.BareMetal.x86/Boot.cs
  Source/Mosa.UnitTests.BareMetal.x86/Mosa.UnitTests.BareMetal.x86.csproj
  Source/Mosa.UnitTests.BareMetal.x86/UnitTestEngine.cs
  Source/Mosa.UnitTests/Basic/ArrayLayoutTests.cs
  Source/Mosa.Utility.Configuration/CommandLineArguments.cs
  Source/Mosa.Utility.Launcher/Starter.cs
  Source/Mosa.Utility.UnitTests/UnitTestEngine.cs
  Source/Mosa.Workspace.Experiment.Debug/Program.cs
Labels: Bug, WIP

#1130 feat: allocate stack for multiboot using bss
  Source/Docs/settings-options.rst
  Source/Mosa.Compiler.Framework/Platform/BaseMultibootStage.cs
  Source/Mosa.Platform.x64/CompilerStages/MultibootStage.cs
  Source/Mosa.Platform.x86/CompilerStages/MultibootStage.cs
  Source/Mosa.Utility.Configuration/Name.cs
Labels: Feature
